<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);CS8618;CS8602;CS8625;CS8604;CS8601;CS8603;CS8629;CS8600;CS8632;CS0162;CS0168;NU1510</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookBlossom.Core\BookBlossom.Core.csproj" />
    <ProjectReference Include="..\BookBlossom.Infrastructure\BookBlossom.Infrastructure.csproj" />
    
    <!-- Ignore dynamic uploads from dotnet watch tracking to prevent workspace desync crash -->
    <Watch Remove="wwwroot\images\Book\**\*" />
    <Watch Remove="wwwroot\samples\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.6.0" />
    <PackageReference Include="itext7" Version="9.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
