<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookBlossom.Core\BookBlossom.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BackgroundJobs\" />
    <Folder Include="Data\Configurations\" />
    <Folder Include="Extensions\" />
    <Folder Include="Services\Storage\" />
    <Folder Include="Services\Payments\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
  </ItemGroup>

</Project>
