<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS8618;CS8602;CS8625;CS8604;CS8601;CS8603;CS8629;CS8600;CS8632;CS0162;CS0168;NU1510</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Entities\" />
    <Folder Include="Enums\" />
    <Folder Include="Constants\" />
    <Folder Include="Exceptions\" />
    <Folder Include="DTOs\" />
    <Folder Include="Interfaces\Infrastructure\" />
    <Folder Include="Interfaces\Services\" />
    <Folder Include="Specifications\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.8" />
  </ItemGroup>

  <!-- Nhằm đọc được file PDF từ request-->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
