// <auto-generated />
using System;
using BookBlossom.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookBlossom.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515163619_SyncServiceModule")]
    partial class SyncServiceModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerDetail", b =>
                {
                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<int>("CurrentMonthThreadCount")
                        .HasColumnType("int");

                    b.Property<int>("CurrentOrderStreak")
                        .HasColumnType("int");

                    b.Property<int>("DailyUndoCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnboardingCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastThreadResetDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastUndoDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalSpending")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CustomerID");

                    b.ToTable("CustomerDetail", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerService", b =>
                {
                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentPackageID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerID");

                    b.HasIndex("CurrentPackageID");

                    b.ToTable("CustomerService", "Service");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.GuestDetail", b =>
                {
                    b.Property<Guid>("GuestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GuestID");

                    b.Property<long?>("ConvertedUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("GuestID");

                    b.HasIndex("ConvertedUserID");

                    b.ToTable("GuestDetail", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.OTPLog", b =>
                {
                    b.Property<long>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<Guid?>("GuestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OTPCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("LogID");

                    b.ToTable("OTPLogs", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ServiceHistory", b =>
                {
                    b.Property<long>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistoryID"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAutoRenew")
                        .HasColumnType("bit");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HistoryID");

                    b.HasIndex("CustomerID");

                    b.ToTable("ServiceHistory", "Service");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ServicePackage", b =>
                {
                    b.Property<long>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PackageID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDay")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ThreadLimit")
                        .HasColumnType("int");

                    b.Property<int>("UndoLimit")
                        .HasColumnType("int");

                    b.HasKey("PackageID");

                    b.ToTable("ServicePackage", "Service");

                    b.HasData(
                        new
                        {
                            PackageID = 1L,
                            Description = "Gói miễn phí: 3 thread/tháng, 2 undo Tindbook.",
                            DurationDay = 0,
                            PackageName = "Free",
                            Price = 0m,
                            ThreadLimit = 3,
                            UndoLimit = 2
                        },
                        new
                        {
                            PackageID = 2L,
                            Description = "Gói Cơ bản: 20 thread/tháng, 5 undo Tindbook.",
                            DurationDay = 30,
                            PackageName = "Basic",
                            Price = 99000m,
                            ThreadLimit = 20,
                            UndoLimit = 5
                        },
                        new
                        {
                            PackageID = 3L,
                            Description = "Gói Chuyên nghiệp: Không giới hạn thread và undo.",
                            DurationDay = 30,
                            PackageName = "Pro",
                            Price = 199000m,
                            ThreadLimit = 999999,
                            UndoLimit = 999999
                        });
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.StaffDetail", b =>
                {
                    b.Property<long>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("ContractType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Department")
                        .HasColumnType("tinyint");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsOnboardingCompleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("KPIScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StaffID");

                    b.ToTable("StaffDetail", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserID"));

                    b.Property<byte>("AccountStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.ToTable("User", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerDetail", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithOne("CustomerDetail")
                        .HasForeignKey("BookBlossom.Core.Entities.CustomerDetail", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerService", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.ServicePackage", "ServicePackage")
                        .WithMany("CustomerServices")
                        .HasForeignKey("CurrentPackageID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithOne("CustomerService")
                        .HasForeignKey("BookBlossom.Core.Entities.CustomerService", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.GuestDetail", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "ConvertedUser")
                        .WithMany("GuestDetails")
                        .HasForeignKey("ConvertedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConvertedUser");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ServiceHistory", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.StaffDetail", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithOne("StaffDetail")
                        .HasForeignKey("BookBlossom.Core.Entities.StaffDetail", "StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ServicePackage", b =>
                {
                    b.Navigation("CustomerServices");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.User", b =>
                {
                    b.Navigation("CustomerDetail")
                        .IsRequired();

                    b.Navigation("CustomerService")
                        .IsRequired();

                    b.Navigation("GuestDetails");

                    b.Navigation("StaffDetail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
