// <auto-generated />
using System;
using BookBlossom.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookBlossom.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260531234517_UpdateAuditLogsTableName")]
    partial class UpdateAuditLogsTableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookBlossom.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogID"));

                    b.Property<byte>("ActionType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SystemAdminID")
                        .HasColumnType("bigint");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("LogID");

                    b.HasIndex("SystemAdminID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Badge", b =>
                {
                    b.Property<long>("BadgeID")
                        .HasColumnType("bigint");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BadgeID");

                    b.ToTable("Badge", "Rank");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.BadgeCustomer", b =>
                {
                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<long>("BadgeID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerID", "BadgeID");

                    b.HasIndex("BadgeID");

                    b.ToTable("CustomerBadge", "Rank");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.BlindBook", b =>
                {
                    b.Property<long>("BlindBookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BlindBookID"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BlindBookRequestStatus")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hashtags")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("RealBookID")
                        .HasColumnType("bigint");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestQuantity")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("BlindBookID");

                    b.HasIndex("RealBookID")
                        .IsUnique();

                    b.ToTable("BlindBook", "Book");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Cart", b =>
                {
                    b.Property<long>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CartID"));

                    b.Property<long?>("BlindBookID")
                        .HasColumnType("bigint");

                    b.Property<long?>("BookID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GuestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("CartID");

                    b.HasIndex("BlindBookID");

                    b.HasIndex("BookID");

                    b.HasIndex("GuestID", "BlindBookID")
                        .IsUnique()
                        .HasFilter("[GuestID] IS NOT NULL AND [BlindBookID] IS NOT NULL");

                    b.HasIndex("GuestID", "BookID")
                        .IsUnique()
                        .HasFilter("[GuestID] IS NOT NULL AND [BookID] IS NOT NULL");

                    b.HasIndex("UserID", "BlindBookID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL AND [BlindBookID] IS NOT NULL");

                    b.HasIndex("UserID", "BookID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL AND [BookID] IS NOT NULL");

                    b.ToTable("Cart", "dbo");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Category", b =>
                {
                    b.Property<long>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Category", "Preference");

                    b.HasData(
                        new
                        {
                            CategoryID = 1L,
                            CategoryName = "Văn học",
                            Description = "Sách Văn học nghệ thuật, tiểu thuyết, thơ ca",
                            Status = (byte)1
                        },
                        new
                        {
                            CategoryID = 2L,
                            CategoryName = "Kỹ năng",
                            Description = "Sách phát triển bản thân, kỹ năng sống và làm việc",
                            Status = (byte)1
                        },
                        new
                        {
                            CategoryID = 3L,
                            CategoryName = "Tâm lý",
                            Description = "Sách tâm lý học, hành vi và nhận thức",
                            Status = (byte)1
                        },
                        new
                        {
                            CategoryID = 4L,
                            CategoryName = "Kinh dị",
                            Description = "Sách thuộc thể loại kinh dị, giật gân và bí ẩn",
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerDetail", b =>
                {
                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<int>("CurrentMonthThreadCount")
                        .HasColumnType("int");

                    b.Property<int>("CurrentOrderStreak")
                        .HasColumnType("int");

                    b.Property<long?>("CurrentPackageID")
                        .HasColumnType("bigint");

                    b.Property<int>("DailyUndoCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnboardingCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastThreadResetDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastUndoDate")
                        .HasColumnType("date");

                    b.Property<long?>("RankID")
                        .HasColumnType("bigint")
                        .HasColumnName("RankID");

                    b.Property<int>("ShareCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSpending")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CustomerID");

                    b.HasIndex("CurrentPackageID");

                    b.HasIndex("RankID");

                    b.ToTable("CustomerDetail", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerPreference", b =>
                {
                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("CustomerPreference", "Preference");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerReputation", b =>
                {
                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<long?>("RankID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReputationMaxStreakStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReputationPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.HasKey("CustomerID");

                    b.HasIndex("RankID")
                        .IsUnique()
                        .HasFilter("[RankID] IS NOT NULL");

                    b.ToTable("CustomerReputation", "Rank");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerService", b =>
                {
                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentPackageID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerID");

                    b.HasIndex("CurrentPackageID");

                    b.ToTable("CustomerService", "Service");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerVoucher", b =>
                {
                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<long>("VoucherID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<long?>("OrderID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("datetime");

                    b.HasKey("CustomerID", "VoucherID");

                    b.HasIndex("OrderID");

                    b.HasIndex("VoucherID");

                    b.ToTable("CustomerVoucher", "Voucher");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.DeliveryAddress", b =>
                {
                    b.Property<long>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AddressID"));

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("DetailAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AddressID");

                    b.ToTable("DeliveryAddress", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.GuestDetail", b =>
                {
                    b.Property<Guid>("GuestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GuestID");

                    b.Property<long?>("ConvertedUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("DailyUndoCount")
                        .HasColumnType("int");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastUndoDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("GuestID");

                    b.HasIndex("ConvertedUserID");

                    b.ToTable("GuestDetail", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.GuestPreference", b =>
                {
                    b.Property<Guid>("GuestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GuestID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("GuestPreference", "Preference");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Importing", b =>
                {
                    b.Property<long>("ImportingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ImportingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImportingID"));

                    b.Property<DateTime?>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ShipDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ImportingID");

                    b.HasIndex("StaffID");

                    b.ToTable("Importing", "Import");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ImportingDetail", b =>
                {
                    b.Property<long>("ImportingID")
                        .HasColumnType("bigint");

                    b.Property<long>("BookID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[UnitPrice] * [Quantity]", true);

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ImportingID", "BookID");

                    b.HasIndex("BookID");

                    b.ToTable("ImportingDetail", "Import");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.MembershipRank", b =>
                {
                    b.Property<long>("RankID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RankID"));

                    b.Property<decimal?>("DiscountRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("MinSpending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<byte?>("RankType")
                        .HasColumnType("tinyint");

                    b.HasKey("RankID");

                    b.ToTable("MembershipRank", "Rank");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.OTPLog", b =>
                {
                    b.Property<long>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<Guid?>("GuestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OTPCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("LogID");

                    b.ToTable("OTPLogs", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Order", b =>
                {
                    b.Property<long>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderID"));

                    b.Property<long?>("AddressID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<byte>("OrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("ShipDetailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ShipReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ShippingFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("VoucherID")
                        .HasColumnType("bigint");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID")
                        .HasDatabaseName("IX_Orders_CustomerID");

                    b.HasIndex("OrderDate")
                        .HasDatabaseName("IX_Orders_OrderDate");

                    b.HasIndex("OrderStatus")
                        .HasDatabaseName("IX_Orders_OrderStatus");

                    b.HasIndex("VoucherID");

                    b.ToTable("Orders", "OrderRequest");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.OrderDetail", b =>
                {
                    b.Property<long>("OrderID")
                        .HasColumnType("bigint");

                    b.Property<long>("BookID")
                        .HasColumnType("bigint");

                    b.Property<long?>("BlindBookID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID", "BookID");

                    b.HasIndex("BlindBookID");

                    b.HasIndex("BookID");

                    b.ToTable("OrderDetail", "OrderRequest");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.RealBook", b =>
                {
                    b.Property<long>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BookID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookID"));

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsContinued")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int");

                    b.Property<string>("SampleFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("BookID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("RealBook", "Book");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Report", b =>
                {
                    b.Property<long>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool?>("IsAccurate")
                        .HasColumnType("bit");

                    b.Property<long>("PostID")
                        .HasColumnType("bigint");

                    b.Property<byte>("Reason")
                        .HasColumnType("tinyint");

                    b.HasKey("ReportID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PostID");

                    b.ToTable("Report", "Thread");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ReputationHistory", b =>
                {
                    b.Property<long>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistoryID"));

                    b.Property<int>("ChangeAmount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ReferenceType")
                        .HasColumnType("tinyint");

                    b.HasKey("HistoryID");

                    b.HasIndex("CustomerID");

                    b.ToTable("ReputationHistory", "Rank");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ReturnRequest", b =>
                {
                    b.Property<long>("ReturnRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReturnRequestID"));

                    b.Property<long>("BookID")
                        .HasColumnType("bigint");

                    b.Property<string>("GatewayTransactionID")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("OrderID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RefundCompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("ResolutionType")
                        .HasColumnType("tinyint");

                    b.Property<int>("ReturnQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ReturnReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ReturnStatus")
                        .HasColumnType("tinyint");

                    b.Property<long?>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<string>("UnboxVideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReturnRequestID");

                    b.HasIndex("BookID");

                    b.HasIndex("OrderID");

                    b.HasIndex("StaffID");

                    b.ToTable("ReturnRequest", "OrderRequest");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Review", b =>
                {
                    b.Property<long>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReviewID"));

                    b.Property<long?>("BlindBookID")
                        .HasColumnType("bigint");

                    b.Property<long?>("BookID")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageVideoPath")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReputationAwarded")
                        .HasColumnType("bit");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Review", "Review");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Role", b =>
                {
                    b.Property<byte>("RoleID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("Role", "UserSystem");

                    b.HasData(
                        new
                        {
                            RoleID = (byte)0,
                            Description = "Quyền Guest",
                            RoleName = "Guest"
                        },
                        new
                        {
                            RoleID = (byte)1,
                            Description = "Quyền Customer",
                            RoleName = "Customer"
                        },
                        new
                        {
                            RoleID = (byte)2,
                            Description = "Quyền Admin",
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ServiceHistory", b =>
                {
                    b.Property<long>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistoryID"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAutoRenew")
                        .HasColumnType("bit");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HistoryID");

                    b.HasIndex("CustomerID");

                    b.ToTable("ServiceHistory", "Service");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ServicePackage", b =>
                {
                    b.Property<long>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PackageID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDay")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ThreadLimit")
                        .HasColumnType("int");

                    b.Property<int>("UndoLimit")
                        .HasColumnType("int");

                    b.HasKey("PackageID");

                    b.ToTable("ServicePackage", "Service");

                    b.HasData(
                        new
                        {
                            PackageID = 1L,
                            Description = "Gói miễn phí: 3 thread/tháng, 2 undo Tindbook.",
                            DurationDay = 0,
                            PackageName = "Free",
                            Price = 0m,
                            ThreadLimit = 3,
                            UndoLimit = 2
                        },
                        new
                        {
                            PackageID = 2L,
                            Description = "Gói Cơ bản: 20 thread/tháng, 5 undo Tindbook.",
                            DurationDay = 30,
                            PackageName = "Basic",
                            Price = 99000m,
                            ThreadLimit = 20,
                            UndoLimit = 5
                        },
                        new
                        {
                            PackageID = 3L,
                            Description = "Gói Chuyên nghiệp: Không giới hạn thread và undo.",
                            DurationDay = 30,
                            PackageName = "Pro",
                            Price = 199000m,
                            ThreadLimit = 999999,
                            UndoLimit = 999999
                        });
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.StaffDetail", b =>
                {
                    b.Property<long>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("ContractType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Department")
                        .HasColumnType("tinyint");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsOnboardingCompleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("KPIScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StaffID");

                    b.ToTable("StaffDetail", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Subscription", b =>
                {
                    b.Property<long>("FollowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FollowID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<long>("TargetID")
                        .HasColumnType("bigint");

                    b.Property<byte>("TargetType")
                        .HasColumnType("tinyint");

                    b.HasKey("FollowID");

                    b.HasIndex("CustomerID", "TargetID", "TargetType");

                    b.ToTable("Subscription", "Notification");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.SwipeLog", b =>
                {
                    b.Property<long>("SwipeLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SwipeLogID"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BlindBookID")
                        .HasColumnType("bigint");

                    b.Property<long?>("BookID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("GuestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SwipeLogID");

                    b.ToTable("SwipeLogs");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.SystemConfiguration", b =>
                {
                    b.Property<long>("ConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConfigID"));

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("GroupType")
                        .HasColumnType("tinyint");

                    b.Property<long>("SystemAdminID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ConfigID");

                    b.HasIndex("SystemAdminID");

                    b.ToTable("SystemConfiguration", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ThreadComment", b =>
                {
                    b.Property<long>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CommentID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<long>("PostID")
                        .HasColumnType("bigint");

                    b.HasKey("CommentID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PostID");

                    b.ToTable("ThreadComment", "Thread");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ThreadImage", b =>
                {
                    b.Property<long>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImageID"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("PostID")
                        .HasColumnType("bigint");

                    b.HasKey("ImageID");

                    b.HasIndex("PostID");

                    b.ToTable("ThreadImage", "Thread");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ThreadPost", b =>
                {
                    b.Property<long>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PostID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Hashtags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("ReportCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PostID");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ReportCount");

                    b.ToTable("ThreadPost", "Thread");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserID"));

                    b.Property<byte>("AccountStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("RoleID")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("User", "UserSystem");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.UserNotification", b =>
                {
                    b.Property<long>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<byte>("NotificationType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ReferenceID")
                        .HasColumnType("int");

                    b.Property<byte?>("ReferenceType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID", "IsRead");

                    b.ToTable("UserFollow", "Notification");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Voucher", b =>
                {
                    b.Property<long>("VoucherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VoucherID"));

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsAutoRefundable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForNewUser")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxUsagePerUser")
                        .HasColumnType("int");

                    b.Property<int>("MembershipRankRequired")
                        .HasColumnType("int");

                    b.Property<decimal>("MinOrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinReputationRequired")
                        .HasColumnType("int");

                    b.Property<long?>("RequiredBadgeID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<byte>("StatusVoucher")
                        .HasColumnType("tinyint");

                    b.Property<int>("TotalLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VoucherName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("VoucherID");

                    b.HasIndex("RequiredBadgeID");

                    b.HasIndex("VoucherCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Voucher_VoucherCode");

                    b.ToTable("Voucher", "Voucher");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.VoucherCategory", b =>
                {
                    b.Property<long>("VoucherID")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.HasKey("VoucherID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("VoucherCategory", "Voucher");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Wishlist", b =>
                {
                    b.Property<long>("WishlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WishlistID"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("BlindBookID")
                        .HasColumnType("bigint");

                    b.Property<long?>("BookID")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("GuestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("WishlistID");

                    b.HasIndex("BlindBookID");

                    b.HasIndex("BookID");

                    b.HasIndex("GuestID", "BlindBookID")
                        .IsUnique()
                        .HasFilter("[GuestID] IS NOT NULL AND [BlindBookID] IS NOT NULL");

                    b.HasIndex("GuestID", "BookID")
                        .IsUnique()
                        .HasFilter("[GuestID] IS NOT NULL AND [BookID] IS NOT NULL");

                    b.HasIndex("UserID", "BlindBookID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL AND [BlindBookID] IS NOT NULL");

                    b.HasIndex("UserID", "BookID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL AND [BookID] IS NOT NULL");

                    b.ToTable("Wishlist", "dbo");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SystemAdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.BadgeCustomer", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.Badge", "Badge")
                        .WithMany("BadgeCustomers")
                        .HasForeignKey("BadgeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.CustomerDetail", "CustomerDetail")
                        .WithMany("BadgeCustomers")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("CustomerDetail");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.BlindBook", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.RealBook", "RealBook")
                        .WithOne("BlindBook")
                        .HasForeignKey("BookBlossom.Core.Entities.BlindBook", "RealBookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RealBook");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Cart", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.BlindBook", "BlindBook")
                        .WithMany()
                        .HasForeignKey("BlindBookID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookBlossom.Core.Entities.RealBook", "Book")
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BlindBook");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerDetail", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.ServicePackage", "ServicePackage")
                        .WithMany("CustomerDetails")
                        .HasForeignKey("CurrentPackageID");

                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithOne("CustomerDetail")
                        .HasForeignKey("BookBlossom.Core.Entities.CustomerDetail", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.MembershipRank", "MembershipRank")
                        .WithMany("CustomerDetails")
                        .HasForeignKey("RankID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MembershipRank");

                    b.Navigation("ServicePackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerPreference", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.Category", "Category")
                        .WithMany("CustomerPreferences")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.CustomerDetail", "CustomerDetail")
                        .WithMany("CustomerPreferences")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CustomerDetail");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerReputation", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.CustomerDetail", "CustomerDetail")
                        .WithMany("CustomerReputations")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.MembershipRank", "MembershipRank")
                        .WithOne("CustomerReputation")
                        .HasForeignKey("BookBlossom.Core.Entities.CustomerReputation", "RankID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomerDetail");

                    b.Navigation("MembershipRank");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerService", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.ServicePackage", "ServicePackage")
                        .WithMany("CustomerServices")
                        .HasForeignKey("CurrentPackageID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.CustomerDetail", null)
                        .WithOne("CustomerService")
                        .HasForeignKey("BookBlossom.Core.Entities.CustomerService", "CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithOne("CustomerService")
                        .HasForeignKey("BookBlossom.Core.Entities.CustomerService", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerVoucher", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.CustomerDetail", "CustomerDetail")
                        .WithMany("CustomerVouchers")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BookBlossom.Core.Entities.Voucher", "Voucher")
                        .WithMany("CustomerVouchers")
                        .HasForeignKey("VoucherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerDetail");

                    b.Navigation("Order");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.GuestDetail", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "ConvertedUser")
                        .WithMany("GuestDetails")
                        .HasForeignKey("ConvertedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConvertedUser");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.GuestPreference", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.GuestDetail", "GuestDetail")
                        .WithMany()
                        .HasForeignKey("GuestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("GuestDetail");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Importing", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.StaffDetail", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ImportingDetail", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.RealBook", "Book")
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.Importing", "Importing")
                        .WithMany("ImportingDetails")
                        .HasForeignKey("ImportingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Importing");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Order", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.Voucher", "Voucher")
                        .WithMany("Orders")
                        .HasForeignKey("VoucherID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.OrderDetail", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.BlindBook", "BlindBook")
                        .WithMany()
                        .HasForeignKey("BlindBookID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BookBlossom.Core.Entities.RealBook", "RealBook")
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlindBook");

                    b.Navigation("Order");

                    b.Navigation("RealBook");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.RealBook", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.Category", "Category")
                        .WithMany("RealBooks")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Report", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.ThreadPost", "Post")
                        .WithMany()
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ReputationHistory", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.CustomerReputation", "CustomerReputation")
                        .WithMany("Histories")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerReputation");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ReturnRequest", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.RealBook", "RealBook")
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.StaffDetail", "StaffDetail")
                        .WithMany()
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("RealBook");

                    b.Navigation("StaffDetail");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Review", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ServiceHistory", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.StaffDetail", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithOne("StaffDetail")
                        .HasForeignKey("BookBlossom.Core.Entities.StaffDetail", "StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Subscription", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.SystemConfiguration", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SystemAdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ThreadComment", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.ThreadPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ThreadImage", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.ThreadPost", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ThreadPost", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.User", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.UserNotification", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Voucher", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.Badge", "RequiredBadge")
                        .WithMany()
                        .HasForeignKey("RequiredBadgeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RequiredBadge");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.VoucherCategory", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBlossom.Core.Entities.Voucher", "Voucher")
                        .WithMany("VoucherCategories")
                        .HasForeignKey("VoucherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Wishlist", b =>
                {
                    b.HasOne("BookBlossom.Core.Entities.BlindBook", "BlindBook")
                        .WithMany()
                        .HasForeignKey("BlindBookID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookBlossom.Core.Entities.RealBook", "Book")
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookBlossom.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BlindBook");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Badge", b =>
                {
                    b.Navigation("BadgeCustomers");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Category", b =>
                {
                    b.Navigation("CustomerPreferences");

                    b.Navigation("RealBooks");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerDetail", b =>
                {
                    b.Navigation("BadgeCustomers");

                    b.Navigation("CustomerPreferences");

                    b.Navigation("CustomerReputations");

                    b.Navigation("CustomerService");

                    b.Navigation("CustomerVouchers");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.CustomerReputation", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Importing", b =>
                {
                    b.Navigation("ImportingDetails");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.MembershipRank", b =>
                {
                    b.Navigation("CustomerDetails");

                    b.Navigation("CustomerReputation");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.RealBook", b =>
                {
                    b.Navigation("BlindBook");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ServicePackage", b =>
                {
                    b.Navigation("CustomerDetails");

                    b.Navigation("CustomerServices");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.ThreadPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.User", b =>
                {
                    b.Navigation("CustomerDetail")
                        .IsRequired();

                    b.Navigation("CustomerService")
                        .IsRequired();

                    b.Navigation("GuestDetails");

                    b.Navigation("StaffDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("BookBlossom.Core.Entities.Voucher", b =>
                {
                    b.Navigation("CustomerVouchers");

                    b.Navigation("Orders");

                    b.Navigation("VoucherCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
